security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt
  #    App\Entity\User: bcrypt

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email

  firewalls:
    login:
      pattern:  ^/login
      stateless: true
      anonymous: true
      json_login:
        check_path:               /login_check
        success_handler:          lexik_jwt_authentication.handler.authentication_success
        failure_handler:          lexik_jwt_authentication.handler.authentication_failure
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern:   ^/
      stateless: true
      anonymous: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/account, roles: IS_AUTHENTICATED_ANONYMOUSLY } #to reset password
    - { path: ^/users, roles: IS_AUTHENTICATED_ANONYMOUSLY , methods: [POST] } #to create user
    - { path: ^/,      roles: IS_AUTHENTICATED_ANONYMOUSLY , methods: [GET] }
    - { path: ^/,      roles: IS_AUTHENTICATED_FULLY , methods: [POST, DELETE, OPTIONS, PUT, PATCH] }

