vich_uploader:
  db_driver: orm # or mongodb or phpcr

mappings:
  subCatPicto:
    uri_prefix: /upload/subCat
    upload_destination: '%kernel.project_dir%/public/upload/subCat'
    namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    inject_on_load: false
    delete_on_update: true
    delete_on_remove: true