monolog:
  handlers:
    main:
      type: stream
      level: debug
      channels: [ "!security", "!deprecation" ]
      path: "%kernel.logs_dir%/%kernel.environment%/main.log"
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", '!security', "!deprecation" ]
    deprecation:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%/deprecations.log"
    deprecation_filter:
      type: filter
      handler: deprecation
      max_level: warning
      channels: [ "php" ]
    security:
      level: debug
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%/security.log"
      channels: [ "security" ]
    doctrine:
      level: debug
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%/doctrine.log"
      channels: [ "doctrine" ]
